apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: backend-tests-go-nwdmqvdd
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: backend-tests-go-nwdmqvdd 
  name: backend-tests-go-nwdmqvdd
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: backend-tests-go-nwdmqvdd
    weight: 100 
